Repository Vikash-8090-Yadav/Solidity-Pathshala, pull requests merged in 2022-08, with the labels that each got.

#15 Add Readme in Hello_World Folder #12
  Level0/Hello_World/README.md
Labels: documentation, HSOC22, HSOC22-Level-1

#22 New readme.md file for level 1 folder and all the grammatical errors solved.
  Level0/Hello_World/Hello_World.sol
  Level1/sendTo_Eather/Readme.md
  Level1/sendTo_Ether/Readme.md
  Level1/sendTo_Ether/SendTo_Ether.sol
  Level2/Marketplace/README.md
  Level2/Voting/README.md
  Level2/banking/banking.sol
Labels: SSOC22-BEGINNER, SSOC22

#26 New readme.md files added inside level 2 folders
  Level2/Marketplace/Marketplace.sol
  Level2/Marketplace/README.md
  Level2/Voting/README.md
  Level2/Voting/Voting.sol
Labels: SSOC22-BEGINNER, SSOC22

#30 Smart Contract "Buy Me A Coffee"
  Level1/Buy Me A Coffee/BuyMeACoffee.sol
  Level1/Buy Me A Coffee/Remix-Contract.png
  Level1/Buy Me A Coffee/readme.md
Labels: SSOC22-BEGINNER, SSOC22

#31 Fixed issue #27
  Level0/Greeting/greeting.sol
  Level0/Hello_World/Hello_World.sol
Labels: SSOC22-BEGINNER, SSOC22

#33 Added 4 codes
  Level0/Check_Palindrome/CheckPalindrome.sol
  Level0/Check_Palindrome/README.md
  Level0/Find_Average/FindAverage.sol
  Level0/Find_Average/README.md
  Level0/Reverse_Digits/README.md
  Level0/Reverse_Digits/ReversingDigits.sol
  Level0/Sum_of_Digits/README.md
  Level0/Sum_of_Digits/SumOfDigits.sol
Labels: SSOC22, SSOC22-INTERMEDIATE

#37 Coin Smart Contract
  Level1/Coin/Coin.sol
  Level1/Coin/Readme.md
Labels: SSOC22-BEGINNER, SSOC22

#43 coin modified
  Level1/Coin/Readme.md
  Level1/Coin_modified/Coinmod.sol
  Level1/Coin_modified/Readme.md
  Level1/Coin_modified/restricted.png
  Level2/Voting/README.md
  Level2/Voting/Voting.sol
Labels: SSOC22-BEGINNER, SSOC22

#54 Modifying sendTo_Ether contract + step by step guide for learners to follow
  Level1/sendTo_Ether/Readme.md
  Level1/sendTo_Ether/SendTo_Ether.sol
Labels: SSOC22-BEGINNER, SSOC22

#60 SSOC22 Logo added
  Images/ssoc22.jpg
  README.md
Labels: SSOC22-BEGINNER, SSOC22
