Repository Vikash-8090-Yadav/Solidity-Pathshala, pull requests merged in 2022-10, with the labels that each got.

#101 Attendance smart contarct
  Level1/Attendence/Attendence.md
  Level1/Attendence/Attendence.sol
Labels: hacktoberfest-accepted

#110 Counter Contract
  Level0/Counter/Counter.sol
  Level0/Counter/README.md
Labels: hacktoberfest-accepted

#105 Completed the issue #103
  Level0/Calculator/Calculatoro.sol
  Level0/Calculator/Readme.md
Labels: hacktoberfest-accepted

#106 added faucet smart contract
  Blog/About Solidity and its Tools/README.md
  Level2/Faucet-smart-contract/Faucet.sol
  Level2/Faucet-smart-contract/README.md
Labels: hacktoberfest-accepted

#114 ToDo List code added
  Level0/Calculator/Readme.md
  Level0/ToDo List/Readme.md
  Level0/ToDo List/todo.sol
Labels: hacktoberfest-accepted

#121 Responsive Images in README.md
  Images/Hsoc22Logo.png
  Images/ssoc22.png
  README.md
Labels: hacktoberfest-accepted, Ready-To-Merge, Excellent

#123 added Multi Sign wallet contract
  Level1/Multi-signature Wallet/MultiSignWallet.sol
  Level1/Multi-signature Wallet/README.md
Labels: hacktoberfest-accepted, Ready-To-Merge, Excellent

#124 Event Organization code add
  Level1/Event_Organization/Readme.md
  Level1/Event_Organization/eventOrganization.sol
Labels: hacktoberfest-accepted, Ready-To-Merge, Excellent

#98 Basic Arithmetic Programs
  Level0/Basics_Solidity_Programs/Add/Readme.md
  Level0/Basics_Solidity_Programs/Add/add.sol
  Level0/Basics_Solidity_Programs/Divide/Div.sol
  Level0/Basics_Solidity_Programs/Divide/Readme.md
  Level0/Basics_Solidity_Programs/Multiply/Mul.sol
  Level0/Basics_Solidity_Programs/Multiply/Readme.md
  Level0/Basics_Solidity_Programs/Sub/Readme.md
  Level0/Basics_Solidity_Programs/Sub/sub.sol
Labels: hacktoberfest-accepted, Excellent

#128 FlashLoan contracts files
  Level1/Flash-Loan/FlashLoan.sol
  Level1/Flash-Loan/README.md
Labels: hacktoberfest-accepted, Excellent

#131 auction Contract
  Level1/SimpleAuction/Readme.md
  Level1/SimpleAuction/auction.sol
Labels: hacktoberfest-accepted, Excellent

#138 Anonymous Polls
  Level2/Anonymous-Polls/README.md
  Level2/Anonymous-Polls/polls.sol
Labels: hacktoberfest-accepted, Excellent

#139 Erc20 token contract
  Level1/ERC20 Tokens/New_ERC20.sol
  Level1/ERC20 Tokens/readme.md
Labels: hacktoberfest-accepted

#137 Library Contract
  Level1/Library Contract/Lib.sol
  Level1/Library Contract/Readme.md
Labels: hacktoberfest-accepted, Excellent

#145 added emergency stop code
  Level1/EmergencyStop/EmergencyStop.sol
  Level1/EmergencyStop/Readme.md
Labels: hacktoberfest-accepted

#146 Timer Smart Contract
  Level1/Timer/Readme.md
  Level1/Timer/timer.sol
Labels: hacktoberfest-accepted, Excellent

#141 ERC-20 Upgradable Smart Contract
  Level2/ERC-20 Upgradable Contract/ERC20UpgradableV1.sol
  Level2/ERC-20 Upgradable Contract/ERC20UpgradableV2.sol
  Level2/ERC-20 Upgradable Contract/deploy.js
  Level2/ERC-20 Upgradable Contract/readme.md
  Level2/ERC-20 Upgradable Contract/upgrade.js
Labels: Changes Requested

#150 Blog Smart Contract
  Level1/Blog/Blog.sol
  Level1/Blog/Readme.md
Labels: hacktoberfest-accepted, Excellent

#154 Stack Implementation Using Solidity
  Level0/Stack/readme.md
  Level0/Stack/stack.sol
Labels: hacktoberfest-accepted, Excellent

#129 Storing Books
  Level1/Storing Books/Books.sol
  Level1/Storing Books/Readme.md
Labels: hacktoberfest-accepted, Excellent

#160 Dutch Auction
  Level1/DutchAuction/DutchAuction.sol
  Level1/DutchAuction/Readme.md
Labels: hacktoberfest-accepted, Excellent

#166 Added Decentralized Bingo Game
  Level1/BingoDecentrailized/Bingo.sol
  Level1/BingoDecentrailized/README.md
  Level1/BingoDecentrailized/Voting.sol
Labels: hacktoberfest-accepted
