Repository Vikash-8090-Yadav/Solidity-Pathshala, pull requests merged in 2023-01, with the labels that each got.

#186 Add files via upload
  Level0/Basic If-Else Codes/Discounted_Price/discounted_price.sol
  Level0/Basic If-Else Codes/Discounted_Price/readme.md
  Level0/Basic If-Else Codes/Get_min/get_min.sol
  Level0/Basic If-Else Codes/Get_min/readme.md
  Level0/Basic If-Else Codes/Greatest_of_two/greatest_of_two.sol
  Level0/Basic If-Else Codes/Greatest_of_two/readme.md
  Level0/Basic If-Else Codes/More_Than_10/moreThan10.sol
  Level0/Basic If-Else Codes/More_Than_10/readme.md
  Level0/Basic If-Else Codes/Odd_Even_Check/odd_even.sol
  Level0/Basic If-Else Codes/Odd_Even_Check/readme.md
  Level0/Basic If-Else Codes/Score_card/Score_Card.sol
  Level0/Basic If-Else Codes/Score_card/readme.md
  Level0/Basic If-Else Codes/Time_Bonus/readme.md
  Level0/Basic If-Else Codes/Time_Bonus/time_bonus.sol
  Level0/Basic If-Else Codes/Voting_Age/voting_age.sol
  Level0/Basic If-Else Codes/Which_Quadrant/which_quad.sol
  Level0/Basic If-Else Codes/Which_day/readme.md
  Level0/Basic If-Else Codes/Which_day/which_day.sol
  Level0/Basic If-Else Codes/leap_year/leap_Year.sol
  Level0/Basic If-Else Codes/leap_year/readme.md
Labels: SWOC23, SWOC23-INTERMEDIATE, Excellent

#188 added sc blog
  Blog/About smart contract/README.md
Labels: SWOC23-BEGINNER, SWOC23

#189 Make changes as per the work assigned
  Level1/FIRsystem/FIR.sol
  Level1/FIRsystem/Readme.md
  Level2/Voting/README.md
  Level2/Voting/Voting.sol
Labels: SWOC23-INTERMEDIATE, Excellent

#191 PR for Issue #180 - updating the hacktoberfest image
  Images/hacktoberfest.jpg
  README.md
Labels: SWOC23-BEGINNER, SWOC23

#193 Smart Contract on Event Organization
  Level2/EventOrganization/eventOrganization.sol
  Level2/EventOrganization/readme.md
Labels: SWOC23, SWOC23-INTERMEDIATE

#194 Lottery smart contract
  Level2/Lottery System/README.md
  Level2/Lottery System/lottery.sol
Labels: SWOC23, SWOC23-INTERMEDIATE

#202 Swoc contribution for Funds Distribution smart contract
  Level1/Equal_Distribution_Of_Funds/Funds.sol
  Level1/Equal_Distribution_Of_Funds/readme.md
Labels: SWOC23-BEGINNER, SWOC23

#205 Rent a Bike smart contract
  Level1/Rent_A_Bike/Rent_a_bike.sol
  Level1/Rent_A_Bike/readme.md
Labels: SWOC23-BEGINNER, SWOC23, Excellent

#215 Added demo video
  Level1/DAO Wallet/DaoAutomatedWallet.sol
  Level1/DAO Wallet/Readme.md
Labels: SWOC23, SWOC23-INTERMEDIATE, Excellent

#212 freelancer smart contract
  Level1/Freelancer/Freelancer.sol
  Level1/Freelancer/Readme.md
  Level1/Freelancer/screenshot.png
Labels: SWOC23
